version: '2.0'
services:
  server:
    build:
      context: ./
      dockerfile: ./server-dockerfile
    container_name: futureserver
    ports:
      - 8080
      - "9339:9229"
    links:
      - mongodb
    depends_on:
      - mongodb
  #   - rsyslog
  #  logging:
  #    driver: syslog
  #    options:
  #      syslog-address: "udp://127.0.0.1:5514"
  #      syslog-facility: daemon
  #      tag: smqserver
    volumes:
      - ../:/var/www/futureboy/
  mongodb:
    build:
      context: ../
      dockerfile: ./docker/mongodb-dockerfile
    container_name: futuremongodb
  #   - rsyslog
  #  logging:
  #    driver: syslog
  #    options:
  #      syslog-address: "udp://127.0.0.1:5514"
  #      syslog-facility: daemon
  #      tag: smqmongodb
    volumes:
      - /data/db
  #rsyslog:
  #  image: voxxit/rsyslog
  #  container_name: smqrsyslog
  #  ports:
  #    - "5514:514/udp"
  #  volumes:
  #    - /tmp:/var/log/syslog
  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx-dockerfile
    container_name: futurenginx
    ports:
      - "8888:80"
    depends_on:
      - server
    links:
      - server:node
    volumes:
      - ../client/:/usr/share/nginx/html:ro
      - ../.config/nginx/sites-available:/etc/nginx/sites-available:ro
      - ../.config/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ../.config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
